name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Ambiente a desplegar (dev, test, prod)"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Serverless
        run: npm install -g serverless

      - name: Deploy Infra
        run: sls deploy --stage ${{ github.event.inputs.stage }} -c infra.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}