AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway + Lambdas CRUD conectados a DynamoDB

Resources:

  ############################
  # API Gateway (REST API)
  ############################
  ItemsApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ItemsApi

  ItemsApiRoot:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ItemsApi
      ParentId: !GetAtt ItemsApi.RootResourceId
      PathPart: items

  ItemsApiItem:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ItemsApi
      ParentId: !Ref ItemsApiRoot
      PathPart: "{id}"

  ############################
  # CREATE Lambda
  ############################
  CreateItemFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CreateItemFunction
      Handler: src/index.createItemsHandler
      Runtime: nodejs18.x
      Timeout: 10
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: lambda-code.zip
      Environment:
        Variables:
          TABLE_NAME: !ImportValue ItemsTableName

  CreateItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ItemsApi
      ResourceId: !Ref ItemsApiRoot
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateItemFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200

  CreateItemPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateItemFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ItemsApi}/*/POST/items

  ############################
  # READ Lambda
  ############################
  ReadItemFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ReadItemFunction
      Handler: src/index.readItemHandler
      Runtime: nodejs18.x
      Timeout: 10
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: lambda-code.zip
      Environment:
        Variables:
          TABLE_NAME: !ImportValue ItemsTableName

  ReadItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ItemsApi
      ResourceId: !Ref ItemsApiItem
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ReadItemFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200

  ReadItemPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ReadItemFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ItemsApi}/*/GET/items/*

  ############################
  # UPDATE Lambda
  ############################
  UpdateItemFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: UpdateItemFunction
      Handler: src/index.updateItemHandler
      Runtime: nodejs18.x
      Timeout: 10
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: lambda-code.zip
      Environment:
        Variables:
          TABLE_NAME: !ImportValue ItemsTableName

  UpdateItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ItemsApi
      ResourceId: !Ref ItemsApiItem
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateItemFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200

  UpdateItemPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UpdateItemFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ItemsApi}/*/PUT/items/*

  ############################
  # DELETE Lambda
  ############################
  DeleteItemFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: DeleteItemFunction
      Handler: src/index.deleteItemHandler
      Runtime: nodejs18.x
      Timeout: 10
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: lambda-code.zip
      Environment:
        Variables:
          TABLE_NAME: !ImportValue ItemsTableName

  DeleteItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ItemsApi
      ResourceId: !Ref ItemsApiItem
      HttpMethod: DELETE
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteItemFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200

  DeleteItemPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeleteItemFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ItemsApi}/*/DELETE/items/*

  ############################
  # LIST Lambda
  ############################
  ListItemsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ListItemsFunction
      Handler: src/index.listItemsHandler
      Runtime: nodejs18.x
      Timeout: 10
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: lambda-code.zip
      Environment:
        Variables:
          TABLE_NAME: !ImportValue ItemsTableName

  ListItemsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ItemsApi
      ResourceId: !Ref ItemsApiRoot
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListItemsFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200

  ListItemsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ListItemsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ItemsApi}/*/GET/items

Outputs:
  ApiId:
    Value: !Ref ItemsApi
    Export:
      Name: ItemsApiId